import fs from 'node:fs/promises';
import * as path from 'node:path';
import openapiTS, { astToString } from 'openapi-typescript';
import ts, { factory } from 'typescript';
import * as child_process from 'node:child_process';

const TYPES_HEADER = `
/**
 * This file is automatically generated by \`scripts/generateSchema.mts\`.
 * Do not edit it manually!
 */
`;

( async function () {

	const specFile = await fs.readFile( path.join( process.cwd(), 'spec.json' ) );
	const spec = JSON.parse( specFile.toString() );

	// Writing types to src/streams/Schema.ts
	const types = await openapiTS( spec );
	await fs.writeFile( 'src/streams/Schema.ts', astToString( types ) );

	// Writing type names and event types to src/streams/index.ts
	const events = Object.keys( spec.paths )
		.map( p => [ p, p.replace( /^\/v2\/stream\//, '' ) ] )
		.filter( ( [ , t ] ) => t !== '{streams}' );
	const eventNames = events.map( ( [ , t ] ) => [
		t, t
			.toLowerCase()
			.replace( /[^a-zA-Z0-9]+([a-z])?/g, ( _, char ) => ( char ? char.toUpperCase() : '' ) )
			.replace( /^./, ( char ) => char.toUpperCase() )
			.replace( /Mediawiki/gi, 'MediaWiki' )
			.replace( /Eventgate/gi, 'EventGate' )
			.replace( /Rdf/gi, 'RDF' )
			.replace( /Recentchange/gi, 'RecentChange' )
	] );

	const typesAst = [
		factory.createImportDeclaration(
			undefined,
			factory.createImportClause(
				undefined,
				undefined,
				factory.createNamedImports( [ factory.createImportSpecifier(
					false,
					undefined,
					factory.createIdentifier( 'paths' )
				) ] )
			),
			factory.createStringLiteral( './Schema' ),
			undefined
		),
		factory.createVariableStatement(
			[ factory.createToken( ts.SyntaxKind.ExportKeyword ) ],
			factory.createVariableDeclarationList(
				[ factory.createVariableDeclaration(
					factory.createIdentifier( 'WikimediaEventStreams' ),
					undefined,
					undefined,
					factory.createTypeAssertion(
						factory.createTypeReferenceNode(
							factory.createIdentifier( 'const' ),
							undefined
						),
						factory.createArrayLiteralExpression(
							events.map( ( [ , v ] ) => factory.createStringLiteral( v ) ),
							true
						)
					)
				) ],
				ts.NodeFlags.Const
			)
		),
		factory.createTypeAliasDeclaration(
			[ factory.createToken( ts.SyntaxKind.ExportKeyword ) ],
			factory.createIdentifier( 'WikimediaEventStream' ),
			undefined,
			factory.createIndexedAccessTypeNode(
				factory.createTypeQueryNode(
					factory.createIdentifier( 'WikimediaEventStreams' ),
					undefined
				),
				factory.createConditionalTypeNode(
					factory.createTypeOperatorNode(
						ts.SyntaxKind.KeyOfKeyword,
						factory.createTypeQueryNode(
							factory.createIdentifier( 'WikimediaEventStreams' ),
							undefined
						)
					),
					factory.createKeywordTypeNode( ts.SyntaxKind.StringKeyword ),
					factory.createTypeOperatorNode(
						ts.SyntaxKind.KeyOfKeyword,
						factory.createTypeQueryNode(
							factory.createIdentifier( 'WikimediaEventStreams' ),
							undefined
						)
					),
					factory.createKeywordTypeNode( ts.SyntaxKind.NeverKeyword )
				)
			)
		),
		factory.createTypeAliasDeclaration(
			[ factory.createToken( ts.SyntaxKind.ExportKeyword ) ],
			factory.createIdentifier( 'WikimediaEventStreamEventTypes' ),
			undefined,
			factory.createTypeLiteralNode( events.map( (
				[ originalPath, trimmedPath ]
			) => factory.createPropertySignature(
				undefined,
				factory.createStringLiteral( trimmedPath ),
				undefined,
				factory.createIndexedAccessTypeNode(
					factory.createIndexedAccessTypeNode(
						factory.createIndexedAccessTypeNode(
							factory.createIndexedAccessTypeNode(
								factory.createIndexedAccessTypeNode(
									factory.createIndexedAccessTypeNode(
										factory.createTypeReferenceNode(
											factory.createIdentifier( 'paths' ),
											undefined
										),
										factory.createLiteralTypeNode(
											factory.createStringLiteral( originalPath )
										)
									),
									factory.createLiteralTypeNode(
										factory.createStringLiteral( 'get' )
									)
								),
								factory.createLiteralTypeNode(
									factory.createStringLiteral( 'responses' )
								)
							),
							factory.createLiteralTypeNode(
								factory.createStringLiteral( '200' )
							)
						),
						factory.createLiteralTypeNode(
							factory.createStringLiteral( 'content' )
						)
					),
					factory.createLiteralTypeNode(
						factory.createStringLiteral( 'application/json' )
					)
				)
			) ) )
		),
		...eventNames.map( ( [ trimmedPath, interfaceName ] ) => factory.createTypeAliasDeclaration(
			[ factory.createToken( ts.SyntaxKind.ExportKeyword ) ],
			factory.createIdentifier( interfaceName + 'Event' ),
			undefined,
			factory.createIndexedAccessTypeNode(
				factory.createTypeReferenceNode(
					factory.createIdentifier( 'WikimediaEventStreamEventTypes' ),
					undefined
				),
				factory.createLiteralTypeNode( factory.createStringLiteral( trimmedPath ) )
			)
		) )
	];

	const guardsAst = [
		factory.createImportDeclaration(
			undefined,
			factory.createImportClause(
				undefined,
				undefined,
				factory.createNamedImports( [ factory.createImportSpecifier(
					false,
					undefined,
					factory.createIdentifier( 'WikimediaEventStreamEventTypes' )
				) ] )
			),
			factory.createStringLiteral( './' ),
			undefined
		),
		factory.createImportDeclaration(
			undefined,
			factory.createImportClause(
				undefined,
				factory.createIdentifier( 'typia' ),
				factory.createNamedImports( [ factory.createImportSpecifier(
					false,
					undefined,
					factory.createIdentifier( 'tags' )
				) ] )
			),
			factory.createStringLiteral( 'typia' ),
			undefined
		),
		...eventNames.map( ( [ trimmedPath, interfaceName ] ) => factory.createVariableStatement(
			[ factory.createToken( ts.SyntaxKind.ExportKeyword ) ],
			factory.createVariableDeclarationList(
				[ factory.createVariableDeclaration(
					factory.createIdentifier(
						'is' +
						// Convert the path to camelCase
						interfaceName +
						'Event'
					),
					undefined,
					undefined,
					factory.createCallExpression(
						factory.createPropertyAccessExpression(
							factory.createIdentifier( 'typia' ),
							factory.createIdentifier( 'createIs' )
						),
						[ factory.createIndexedAccessTypeNode(
							factory.createTypeReferenceNode(
								factory.createIdentifier( 'WikimediaEventStreamEventTypes' ),
								undefined
							),
							factory.createLiteralTypeNode( factory.createStringLiteral(
								trimmedPath
							) )
						) ],
						[]
					)
				) ],
				ts.NodeFlags.Const
			)
		) ),
		factory.createVariableStatement(
			[ factory.createToken( ts.SyntaxKind.ExportKeyword ) ],
			factory.createVariableDeclarationList(
				[ factory.createVariableDeclaration(
					factory.createIdentifier( 'typeGuards' ),
					undefined,
					undefined,
					factory.createObjectLiteralExpression(
						eventNames.map( ( [
							trimmedPath, interfaceName
						] ) => factory.createPropertyAssignment(
							factory.createStringLiteral( trimmedPath ),
							factory.createIdentifier( 'is' + interfaceName + 'Event' )
						) ),
						true
					)
				) ],
				ts.NodeFlags.Const
			)
		)
	];

	const printer = ts.createPrinter( {
		newLine: ts.NewLineKind.LineFeed
	} );

	const typesFile = ts.createSourceFile(
		'index.ts',
		'',
		ts.ScriptTarget.ESNext,
		false,
		ts.ScriptKind.TS
	);
	const typesContent = typesAst.map( node => printer.printNode(
		ts.EmitHint.Unspecified,
		node,
		typesFile
	) ).join( '\n' );
	await fs.writeFile( 'src/streams/index.ts', TYPES_HEADER.trim() + '\n' + typesContent );

	const guardsFile = ts.createSourceFile(
		'Guards.ts',
		'',
		ts.ScriptTarget.ESNext,
		false,
		ts.ScriptKind.TS
	);
	const guardsContent = guardsAst.map( node => printer.printNode(
		ts.EmitHint.Unspecified,
		node,
		guardsFile
	) ).join( '\n' );
	await fs.writeFile( 'src/streams/Guards.ts', TYPES_HEADER.trim() + '\n' + guardsContent );

	// Generating type guards
	// eslint-disable-next-line camelcase
	child_process.execSync(
		'npx typia generate --input src/streams/ --output tmp/ --project tsconfig.typia.json'
	);
	// Moving the generated type guards to src/streams/index.ts
	await fs.copyFile(
		'tmp/Guards.ts',
		'src/streams/Guards.ts'
	);

	let guardsFileContent = ( await fs.readFile( 'src/streams/Guards.ts' ) ).toString();

	// Removing the typia import
	guardsFileContent = guardsFileContent
		.replace(
			/^import typia,\s*{\s*tags\s*} from ['"]typia['"];$/gm,
			''
		);

	await fs.writeFile(
		'src/streams/Guards.ts',
		guardsFileContent
	);
	// Removing the temporary directory
	await fs.rm( 'tmp', { recursive: true, force: true } );
}() );
