/**
 * This file is automatically generated by `scripts/generateSchema.mts`.
 * Do not edit it manually!
 */
import { paths } from "./Schema";
export const WikimediaEventStreams = <const>[
    "eventgate-main.test.event",
    "mediainfo-streaming-updater.mutation.v2",
    "mediawiki.page-create",
    "mediawiki.page-delete",
    "mediawiki.page-links-change",
    "mediawiki.page-move",
    "mediawiki.page-properties-change",
    "mediawiki.page-undelete",
    "mediawiki.page_change.v1",
    "mediawiki.page_revert_risk_prediction_change.v1",
    "mediawiki.recentchange",
    "mediawiki.revision-create",
    "mediawiki.revision-tags-change",
    "mediawiki.revision-visibility-change",
    "page-create",
    "page-delete",
    "page-links-change",
    "page-move",
    "page-properties-change",
    "page-undelete",
    "rdf-streaming-updater.mutation-main.v2",
    "rdf-streaming-updater.mutation-scholarly.v2",
    "rdf-streaming-updater.mutation.v2",
    "recentchange",
    "revision-create",
    "test"
];
export type WikimediaEventStream = (typeof WikimediaEventStreams)[keyof typeof WikimediaEventStreams extends string ? keyof typeof WikimediaEventStreams : never];
export type WikimediaEventStreamEventTypes = {
    "eventgate-main.test.event": paths["/v2/stream/eventgate-main.test.event"]["get"]["responses"]["200"]["content"]["application/json"];
    "mediainfo-streaming-updater.mutation.v2": paths["/v2/stream/mediainfo-streaming-updater.mutation.v2"]["get"]["responses"]["200"]["content"]["application/json"];
    "mediawiki.page-create": paths["/v2/stream/mediawiki.page-create"]["get"]["responses"]["200"]["content"]["application/json"];
    "mediawiki.page-delete": paths["/v2/stream/mediawiki.page-delete"]["get"]["responses"]["200"]["content"]["application/json"];
    "mediawiki.page-links-change": paths["/v2/stream/mediawiki.page-links-change"]["get"]["responses"]["200"]["content"]["application/json"];
    "mediawiki.page-move": paths["/v2/stream/mediawiki.page-move"]["get"]["responses"]["200"]["content"]["application/json"];
    "mediawiki.page-properties-change": paths["/v2/stream/mediawiki.page-properties-change"]["get"]["responses"]["200"]["content"]["application/json"];
    "mediawiki.page-undelete": paths["/v2/stream/mediawiki.page-undelete"]["get"]["responses"]["200"]["content"]["application/json"];
    "mediawiki.page_change.v1": paths["/v2/stream/mediawiki.page_change.v1"]["get"]["responses"]["200"]["content"]["application/json"];
    "mediawiki.page_revert_risk_prediction_change.v1": paths["/v2/stream/mediawiki.page_revert_risk_prediction_change.v1"]["get"]["responses"]["200"]["content"]["application/json"];
    "mediawiki.recentchange": paths["/v2/stream/mediawiki.recentchange"]["get"]["responses"]["200"]["content"]["application/json"];
    "mediawiki.revision-create": paths["/v2/stream/mediawiki.revision-create"]["get"]["responses"]["200"]["content"]["application/json"];
    "mediawiki.revision-tags-change": paths["/v2/stream/mediawiki.revision-tags-change"]["get"]["responses"]["200"]["content"]["application/json"];
    "mediawiki.revision-visibility-change": paths["/v2/stream/mediawiki.revision-visibility-change"]["get"]["responses"]["200"]["content"]["application/json"];
    "page-create": paths["/v2/stream/page-create"]["get"]["responses"]["200"]["content"]["application/json"];
    "page-delete": paths["/v2/stream/page-delete"]["get"]["responses"]["200"]["content"]["application/json"];
    "page-links-change": paths["/v2/stream/page-links-change"]["get"]["responses"]["200"]["content"]["application/json"];
    "page-move": paths["/v2/stream/page-move"]["get"]["responses"]["200"]["content"]["application/json"];
    "page-properties-change": paths["/v2/stream/page-properties-change"]["get"]["responses"]["200"]["content"]["application/json"];
    "page-undelete": paths["/v2/stream/page-undelete"]["get"]["responses"]["200"]["content"]["application/json"];
    "rdf-streaming-updater.mutation-main.v2": paths["/v2/stream/rdf-streaming-updater.mutation-main.v2"]["get"]["responses"]["200"]["content"]["application/json"];
    "rdf-streaming-updater.mutation-scholarly.v2": paths["/v2/stream/rdf-streaming-updater.mutation-scholarly.v2"]["get"]["responses"]["200"]["content"]["application/json"];
    "rdf-streaming-updater.mutation.v2": paths["/v2/stream/rdf-streaming-updater.mutation.v2"]["get"]["responses"]["200"]["content"]["application/json"];
    "recentchange": paths["/v2/stream/recentchange"]["get"]["responses"]["200"]["content"]["application/json"];
    "revision-create": paths["/v2/stream/revision-create"]["get"]["responses"]["200"]["content"]["application/json"];
    "test": paths["/v2/stream/test"]["get"]["responses"]["200"]["content"]["application/json"];
};
export type EventGateMainTestEventEvent = WikimediaEventStreamEventTypes["eventgate-main.test.event"];
export type MediainfoStreamingUpdaterMutationV2Event = WikimediaEventStreamEventTypes["mediainfo-streaming-updater.mutation.v2"];
export type MediaWikiPageCreateEvent = WikimediaEventStreamEventTypes["mediawiki.page-create"];
export type MediaWikiPageDeleteEvent = WikimediaEventStreamEventTypes["mediawiki.page-delete"];
export type MediaWikiPageLinksChangeEvent = WikimediaEventStreamEventTypes["mediawiki.page-links-change"];
export type MediaWikiPageMoveEvent = WikimediaEventStreamEventTypes["mediawiki.page-move"];
export type MediaWikiPagePropertiesChangeEvent = WikimediaEventStreamEventTypes["mediawiki.page-properties-change"];
export type MediaWikiPageUndeleteEvent = WikimediaEventStreamEventTypes["mediawiki.page-undelete"];
export type MediaWikiPageChangeV1Event = WikimediaEventStreamEventTypes["mediawiki.page_change.v1"];
export type MediaWikiPageRevertRiskPredictionChangeV1Event = WikimediaEventStreamEventTypes["mediawiki.page_revert_risk_prediction_change.v1"];
export type MediaWikiRecentChangeEvent = WikimediaEventStreamEventTypes["mediawiki.recentchange"];
export type MediaWikiRevisionCreateEvent = WikimediaEventStreamEventTypes["mediawiki.revision-create"];
export type MediaWikiRevisionTagsChangeEvent = WikimediaEventStreamEventTypes["mediawiki.revision-tags-change"];
export type MediaWikiRevisionVisibilityChangeEvent = WikimediaEventStreamEventTypes["mediawiki.revision-visibility-change"];
export type PageCreateEvent = WikimediaEventStreamEventTypes["page-create"];
export type PageDeleteEvent = WikimediaEventStreamEventTypes["page-delete"];
export type PageLinksChangeEvent = WikimediaEventStreamEventTypes["page-links-change"];
export type PageMoveEvent = WikimediaEventStreamEventTypes["page-move"];
export type PagePropertiesChangeEvent = WikimediaEventStreamEventTypes["page-properties-change"];
export type PageUndeleteEvent = WikimediaEventStreamEventTypes["page-undelete"];
export type RDFStreamingUpdaterMutationMainV2Event = WikimediaEventStreamEventTypes["rdf-streaming-updater.mutation-main.v2"];
export type RDFStreamingUpdaterMutationScholarlyV2Event = WikimediaEventStreamEventTypes["rdf-streaming-updater.mutation-scholarly.v2"];
export type RDFStreamingUpdaterMutationV2Event = WikimediaEventStreamEventTypes["rdf-streaming-updater.mutation.v2"];
export type RecentChangeEvent = WikimediaEventStreamEventTypes["recentchange"];
export type RevisionCreateEvent = WikimediaEventStreamEventTypes["revision-create"];
export type TestEvent = WikimediaEventStreamEventTypes["test"];