name: Monitor for spec changes

on:
    schedule:
        - cron: '42 6 */2 * *'

jobs:
    spec:
        name: Verify spec
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   run: |
                    EXPECT="$( cat spec.json | sha1sum )"
                    ACTUAL="$( curl https://stream.wikimedia.org/?spec | sha1sum )"
                    echo "Expected: $EXPECT"
                    echo "Actual:   $ACTUAL"
                    if [[ "$EXPECT" != "$ACTUAL" ]]; then
                        echo "Spec has changed. Please update the code."
                        echo "Update with \`curl https://stream.wikimedia.org/?spec > spec.json\`"
                        exit 1
                    fi
